### ISSUE TITLE
Working Mac App

### ISSUE THREAD

**Issue by BokBoy** [Rocky-Studios/ManimGUI#6]
Development for Macintosh based systems ~~and/or iPadOS Systems~~

Google, I'll work on this myself (as I'm the only one with a mac)

**Comment by BokBoy** [comment]
iPadOS Systems are sadly out of the context (Apple Developer costs a bit doesn't it...)

**Comment by BokBoy** [comment]
Waiting for @RS-GoogleCoder to finish Windows App.

FYI, iOS devices and iPadOS devices are out of context. 
This Mac App will most likely be available to pre-release on Apple Silicon Macs first, before a release is made available with Intel and Silicon (Universal)

**Comment by RS-GoogleCoder** [comment]
I made a mac branch for you to work on.
https://github.com/Rocky-Studios/ManimGUI/tree/mac

It's gonna be ages before the windows app is done, you might as well start work

**Comment by BokBoy** [comment]
Ging gong.
Why
Why
Why
Why
(i'm gonna spam you on discord later :p)

**Comment by BokBoy** [comment]
Yes another way to annoy @RS-GoogleCoder 

![image](https://github.com/user-attachments/assets/4a0f91fe-30fe-45eb-962a-f2067d31564e)
Here's another reminder that I seriously need you to figure this out, its not letting me add any dependencies!
And push those changes.
@RS-GoogleCoder 
@RS-GoogleCoder

**Comment by RS-GoogleCoder** [comment]
Hello I pushed and merged my changes. Idk if it will fix it but it's there now

**Comment by RS-GoogleCoder** [comment]
Mac port no longer required because we using godot
